[package]
name = "askama_derive"
version = "0.10.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[features]
iron = []
rocket = []
actix-web = []
gotham = []
warp = []

[dependencies]
askama_shared = { version = "0.10", path = "../askama_shared" }
proc-macro2 = "1"
quote = "1"
syn = "1"
